"""
run_model_ollama.py
===================
Interactive script to run Qwen via Ollama (LOCAL).

100% LOCAL — No OpenAI, no internet, no API keys.
Uses Python 'requests' to talk to Ollama at http://localhost:11434

Setup:
    1. Install Ollama
    2. ollama pull qwen:0.5b
    3. ollama serve
    4. pip install requests
    5. python run_model_ollama.py
"""

import requests
from datetime import datetime
import time
import os
import sys

# ── Config ─────────────────────────────────────────────
OLLAMA_URL   = "http://localhost:11434"
MODEL_NAME   = "qwen:0.5b"   # change if you use another model
TEMPERATURE  = 0.7
MAX_TOKENS   = 1024

OUTPUT_FILE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "prompts_and_responses.md"
)
# ───────────────────────────────────────────────────────

CATEGORIES = [
    "Coding",
    "General Knowledge / QA",
    "Reasoning",
    "Visual Question Answering",
    "Other",
]

BANNER = """
╔══════════════════════════════════════════════════════╗
║        Qwen (Ollama) — Local AI Interface            ║
║        100% Local — No internet, No APIs             ║
║   Prompts auto-saved to prompts_and_responses.md     ║
╚══════════════════════════════════════════════════════╝
"""


# ── Connection Check ───────────────────────────────────
def check_connection():
    print(f"  Connecting to Ollama at {OLLAMA_URL} ...", end="", flush=True)
    try:
        resp = requests.get(f"{OLLAMA_URL}/api/tags", timeout=5)
        resp.raise_for_status()
        print(" Connected\n")
    except Exception:
        print("\n\n  Could not connect to Ollama.")
        print("  -> Run: ollama serve\n")
        sys.exit(1)


# ── Category Picker ────────────────────────────────────
def pick_category():
    print("  Select a category:")
    for i, cat in enumerate(CATEGORIES, 1):
        print(f"    [{i}] {cat}")

    while True:
        choice = input("  Enter number (1-5): ").strip()
        if choice.isdigit() and 1 <= int(choice) <= len(CATEGORIES):
            return CATEGORIES[int(choice) - 1]
        print("  Invalid choice, try again.")


# ── Query Ollama ───────────────────────────────────────
def query_model(prompt):
    url = f"{OLLAMA_URL}/api/chat"

    payload = {
        "model": MODEL_NAME,
        "messages": [
            {"role": "user", "content": prompt}
        ],
        "options": {
            "temperature": TEMPERATURE,
            "num_predict": MAX_TOKENS
        },
        "stream": False
    }

    start = time.time()

    response = requests.post(url, json=payload, timeout=300)
    response.raise_for_status()

    elapsed = round(time.time() - start, 2)

    data = response.json()
    text = data["message"]["content"].strip()

    return text, elapsed


# ── Save Output ────────────────────────────────────────
def save_to_md(category, prompt, response, elapsed, evaluation, notes):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    entry = f"""
## [{category}] — {timestamp}

**Prompt:**
{prompt}

**Model Response:**
{response}

**Response Time:** {elapsed}s
**Evaluation:** {evaluation}
**Notes:** {notes}

---
"""

    with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
        f.write(entry)

    print(f"\n  Saved to {OUTPUT_FILE}")


# ── Init File ──────────────────────────────────────────
def init_output_file():
    if not os.path.exists(OUTPUT_FILE):
        with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
            f.write("# Prompts and Responses — Qwen (Ollama)\n\n")
            f.write("> Auto-generated by run_model_ollama.py\n\n")
            f.write("---\n")


# ── Main Loop ──────────────────────────────────────────
def main():
    print(BANNER)

    init_output_file()
    check_connection()

    print(f"  Model   : {MODEL_NAME}")
    print(f"  Temp    : {TEMPERATURE}")
    print(f"  Output  : {OUTPUT_FILE}")
    print()
    print("  Type your prompt, or type 'quit' to exit.")
    print("-" * 54)

    while True:
        print()

        category = pick_category()

        print()
        prompt = input("  Enter your prompt:\n  > ").strip()

        if prompt.lower() in ("quit", "exit", "q"):
            print(f"\n  Goodbye! All responses saved to {OUTPUT_FILE}")
            break

        if not prompt:
            print("  Empty prompt, skipping.")
            continue

        print("\n  Querying Ollama... (may take time on CPU)\n")

        try:
            response, elapsed = query_model(prompt)
        except requests.exceptions.Timeout:
            print("  Request timed out. Model may still be loading.")
            continue
        except Exception as e:
            print(f"  Error: {e}")
            continue

        print("-" * 54)
        print("  MODEL RESPONSE:")
        print("-" * 54)
        print(response)
        print("-" * 54)
        print(f"  Response time: {elapsed}s")

        print()
        print("  Rate the response:")
        print("    [1] Correct / Good")
        print("    [2] Partially correct")
        print("    [3] Incorrect / Hallucinated")
        print("    [4] Incomplete")

        eval_map = {
            "1": "Correct / Good",
            "2": "Partially correct",
            "3": "Incorrect / Hallucinated",
            "4": "Incomplete",
        }

        eval_choice = input("  Enter number (1-4): ").strip()
        evaluation = eval_map.get(eval_choice, "Not rated")

        notes = input("  Add a short note (or press Enter to skip): ").strip()
        if not notes:
            notes = "-"

        save_to_md(category, prompt, response, elapsed, evaluation, notes)

        again = input("\n  Run another prompt? (y/n): ").strip().lower()
        if again != "y":
            print(f"\n  All done! Results saved to: {OUTPUT_FILE}")
            break

        print("\n" + "-" * 54)


# ── Run ────────────────────────────────────────────────
if __name__ == "__main__":
    main()